/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dictionary;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author ishay
 */
public class Dictionary extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary
     */
    public Dictionary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextPane();
        txt = new javax.swing.JTextField();
        Heading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 590, 290));

        jScrollPane2.setViewportView(txtResult);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 590, 30));

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyTyped(evt);
            }
        });
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 591, 28));

        Heading.setFont(new java.awt.Font("Helvetica", 0, 11)); // NOI18N
        Heading.setText("Phone Directory");
        Heading.setMaximumSize(new java.awt.Dimension(79, 50));
        Heading.setMinimumSize(new java.awt.Dimension(79, 50));
        Heading.setPreferredSize(new java.awt.Dimension(79, 50));
        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 11, 90, 56));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private DefaultListModel<String> mod;
    private ArrayList<Node> arr;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        mod = new DefaultListModel<>();
        list.setModel(mod);
        arr = new ArrayList<>();
        Data obj;

        BinaryTree theTree = new BinaryTree();

        theTree.addNode("Jake", "+923115769285");

        theTree.addNode("Karthik", "+923002598763");

        theTree.addNode("Jennifer", "+926558731657");

        theTree.addNode("Jane", "+928956253145");

        theTree.addNode("Peter", "+925896310254");
        
        theTree.addNode("Ahmed", "+926589732512");

        theTree.addNode("Inam", "+926598730125");
        
        theTree.addNode("Salman", "+926556980125");


        // Different ways to traverse binary trees
        // theTree.inOrderTraverseTree(theTree.root);
        // theTree.preorderTraverseTree(theTree.root);
        // theTree.postOrderTraverseTree(theTree.root);
        // Find the node with key 75
        ArrayList<Node> arrayList = theTree.preorderTraverseTree(theTree.root);

        Node arrNew[] = new Node[arrayList.size()];
        for (int i = 0; i < arrayList.size(); i++) {
            arrNew[i] = arrayList.get(i);
        }

        QuickSort obj1 = new QuickSort(arrNew);
        obj1.quickSort(0, arrNew.length - 1);
        for (Node elem : obj1.arr) {
            arr.add(elem);
            mod.addElement(elem.name);
        }

//        obj = new Data("Apple", "juicy fruit");
//        arr.add(obj);
//        mod.addElement(obj.getText());
//
//        obj = new Data("Boy", "A male child");
//        arr.add(obj);
//        mod.addElement(obj.getText());
    }//GEN-LAST:event_formWindowOpened

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
        // TODO add your handling code here:
        if (!list.isSelectionEmpty()) {
            int index = list.getSelectedIndex();
            txtResult.setText(arr.get(index).number);
        }
    }//GEN-LAST:event_listValueChanged

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyTyped
        // TODO add your handling code here:
        String text = txt.getText().trim();
        text += evt.getKeyChar();
        text = text.trim().toLowerCase();
        for (int i = 0; i < mod.size(); i++) {
            String val = "" + mod.getElementAt(i);
            val = val.toLowerCase();

            if ("".equals(text)) {
                txtResult.setText("");
                list.clearSelection();
                return;
            }
            if (val.startsWith(text)) {
                list.setSelectedIndex(i);
                return;
            }
        }
        txtResult.setText("This name not found");
        list.clearSelection();
    }//GEN-LAST:event_txtKeyTyped

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField txt;
    private javax.swing.JTextPane txtResult;
    // End of variables declaration//GEN-END:variables
}
